SFAdapter/sf_package/src/objects/AdminCredentials__c.object
<CustomObject>
    <fields>
        <fullName>CommentsLabel__c</fullName>
        <description>Call log comments label</description>
        <label>CommentsLabel</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Login__c</fullName>
        <label>Login</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServerURL__c</fullName>
        <description>Fdp server URL</description>
        <label>ServerURL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Server login token.</description>
        <inlineHelpText>Server login token.</inlineHelpText>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>FonAdminCredential</label>
    <nameField>
        <label>AdminCredentials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FonAdminCredentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFAdapter/sf_package/src/objects/HudAccount__c.object
<CustomObject>
    <fields>
        <fullName>UserHudLogin__c</fullName>
        <label>UserHudLogin</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>HudAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FonHudAccount</label>
    <nameField>
        <label>HudAccounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FonHudAccount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFAdapter/sf_package/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

SFAdapter/sf_package/src/classes/FonLoginTest.cls
@isTest
public class FonLoginTest{
    private final static String ADM_LOGIN = 'Test login';
    private final static String ADM_PASSWRD = 'Test password';
    private final static String SERVER_URL = 'http://test.com/test.html';
    private final static String USER_HUD_LOGIN = 'Test hud login';
    private final static String COMMENTS_FIELD = 'TestField';
    
    public class Info {
        String admLogin;
        String admPassword;
        String serverURL;
        String hudLogin;
        String email;
    }
    
    public class AdmInfo {
        String admLogin;
        String admPassword;
        String serverURL;
    }
    
    static testmethod void validateGetLoginInfo() {
        System.assertEquals('{\n}', FonLogin.getLoginInfo());
        
        final AdminCredentials__c cred = new AdminCredentials__c();
        cred.Login__c = ADM_LOGIN;
        cred.Token__c = ADM_PASSWRD;
        cred.ServerURL__c = SERVER_URL;
        insert cred;
        
        AdmInfo atest = (AdmInfo)JSON.deserialize(FonLogin.getLoginInfo(), AdmInfo.class);
        System.assertEquals(ADM_LOGIN, atest.admLogin);
        System.assertEquals(ADM_PASSWRD, atest.admPassword);
        System.assertEquals(SERVER_URL, atest.serverURL);
        
        final HudAccount__c userLogin = new HudAccount__c();
        userLogin.UserHudLogin__c = USER_HUD_LOGIN;
        userLogin.UserId__c = UserInfo.getUserId();
        insert userLogin;
        
        Info test = (Info)JSON.deserialize(FonLogin.getLoginInfo(), Info.class);
        System.assertEquals(ADM_LOGIN, test.admLogin);
        System.assertEquals(ADM_PASSWRD, test.admPassword);
        System.assertEquals(SERVER_URL, test.serverURL);
        System.assertEquals(USER_HUD_LOGIN, test.hudLogin); 
        List<User> users = [SELECT Username FROM User WHERE Id =: UserInfo.getUserId()];
        System.assertEquals(users.size(), 1); 
        System.debug(users[0]);
        System.assertEquals(users[0].Username, test.email); 
    }
    
    static testmethod void validateGetCalllogFieldName() {
        System.assertEquals(null, FonLogin.getCalllogFieldName());
        
        final AdminCredentials__c cred = new AdminCredentials__c();
        cred.Login__c = ADM_LOGIN;
        cred.Token__c = ADM_PASSWRD;
        cred.ServerURL__c = SERVER_URL;
        cred.CommentsLabel__c = COMMENTS_FIELD;
        insert cred;
        System.assertEquals(null, FonLogin.getCalllogFieldName()); 
        
    }
}