SFAdapter/sf_package/src/objects/AdminCredentials__c.object
<CustomObject>
    <fields>
        <fullName>CommentsLabel__c</fullName>
        <description>Call log comments label</description>
        <label>CommentsLabel</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Login__c</fullName>
        <label>Login</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServerURL__c</fullName>
        <description>Fdp server URL</description>
        <label>ServerURL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Server login token.</description>
        <inlineHelpText>Server login token.</inlineHelpText>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>FonAdminCredential</label>
    <nameField>
        <label>AdminCredentials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FonAdminCredentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFAdapter/sf_package/src/objects/HudAccount__c.object
<CustomObject>
    <fields>
        <fullName>UserHudLogin__c</fullName>
        <label>UserHudLogin</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>HudAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FonHudAccount</label>
    <nameField>
        <label>HudAccounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FonHudAccount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFAdapter/sf_package/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

SFAdapter/sf_package/src/classes/FonLogin.cls
global with sharing class FonLogin{
    private final static String ADM_LOGIN = 'admLogin';
    private final static String ADM_PASSWRD = 'admPassword';
    private final static String SERVER_URL = 'serverUrl';
    private final static String USER_HUD_LOGIN = 'hudLogin';
    private final static String EMAIL = 'email';
    
    global static String getLoginInfo() {
       final List<AdminCredentials__c> admCred = [SELECT Login__c, Token__c, ServerURL__c FROM AdminCredentials__c LIMIT 1];
       final List<HudAccount__c> hudLogin = [SELECT UserHudLogin__c FROM HudAccount__c WHERE UserId__c =: UserInfo.getUserId() LIMIT 1];
       final List<User> users = [SELECT Username FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
       
       JSONGenerator res = JSON.createGenerator(true);
       res.writeStartObject();
         if(0 != admCred.size()) {
           if(admCred[0].Login__c != null) {
               res.writeStringField(ADM_LOGIN, admCred[0].Login__c);   
           }
           if(admCred[0].Token__c != null) {
                res.writeStringField(ADM_PASSWRD, admCred[0].Token__c);
           }
           if(admCred[0].ServerURL__c != null) {
               res.writeStringField(SERVER_URL, admCred[0].ServerURL__c);
           } 
           if(0 != users.size()) {
                res.writeStringField(EMAIL, users[0].Username);
           }
           if(0 != hudLogin.size()) {
                res.writeStringField(USER_HUD_LOGIN, hudLogin[0].UserHudLogin__c);
           }
         }    
       return res.getAsString();
    }
    
    global static String getCalllogFieldName() {
       final List<AdminCredentials__c> admCred = [SELECT CommentsLabel__c FROM AdminCredentials__c LIMIT 1];
       String label = null;
       if(admCred != null && admCred.size() > 0) {
            label = admCred[0].CommentsLabel__c;
       }
       if(!String.isEmpty(label)) {
           final Map<String, SobjectField> fieldMap = Task.getsObjectType().getDescribe().Fields.getMap();          
           if(fieldMap.containsKey(label.toLowerCase())) {
               return label;
           }
       }
       return null;
    }
}